### ISSUE TITLE
This may not work as intended.

### ISSUE THREAD

**Issue by katekyy** [eliasjonsson023/lidshutsleep#1]
https://github.com/eliasjonsson023/lidshutsleep/blob/e4862dda8b2a34fae7a2a2244c0b280c3ae33c6e/src/main.rs#L9

On my system, `"/proc/acpi/button/lid/LID0/state"` should be `"/proc/acpi/button/lid/LID/state"` ("LID" without "0")

**Comment by eliasjonsson023** [comment]
Forgot to add text to the review so adding it here instead:
It works! How about removing the debug output? After that I think we are good to merge.

**Comment by katekyy** [comment]
> Forgot to add text to the review so adding it here instead:
> It works! How about removing the debug output? After that I think we are good to merge.

I removed debug output.
